language: python
python:
  - "2.6"
  - "2.7"


install:
- true # use this to skip the install step or add any commands required to install your project dependencies

script:
- python test.py
 # or any other command you'd like to run your tests with
